//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetCapture.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUser
    {
        public AppUser()
        {
            this.GSS_Invoice = new HashSet<GSS_Invoice>();
            this.GSS_SalesTbl = new HashSet<GSS_SalesTbl>();
            this.GSS_SalesTbl1 = new HashSet<GSS_SalesTbl>();
            this.GSS_SalesTbl2 = new HashSet<GSS_SalesTbl>();
            this.GSS_SalesTbl3 = new HashSet<GSS_SalesTbl>();
            this.GSS_SalesTbl4 = new HashSet<GSS_SalesTbl>();
        }
    
        public int ID { get; set; }
        public string FullName { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public string UserRole { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public string ModifiedBy { get; set; }
        public string Email { get; set; }
        public string StaffID { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual ICollection<GSS_Invoice> GSS_Invoice { get; set; }
        public virtual ICollection<GSS_SalesTbl> GSS_SalesTbl { get; set; }
        public virtual ICollection<GSS_SalesTbl> GSS_SalesTbl1 { get; set; }
        public virtual ICollection<GSS_SalesTbl> GSS_SalesTbl2 { get; set; }
        public virtual ICollection<GSS_SalesTbl> GSS_SalesTbl3 { get; set; }
        public virtual ICollection<GSS_SalesTbl> GSS_SalesTbl4 { get; set; }
    }
}
