//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetCapture.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        public Asset()
        {
            this.AssetBudgets = new HashSet<AssetBudget>();
        }
    
        public int ID { get; set; }
        public string AssetName { get; set; }
        public Nullable<int> AssetTypeID { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string DelFlg { get; set; }
    
        public virtual AssetType AssetType { get; set; }
        public virtual ICollection<AssetBudget> AssetBudgets { get; set; }
    }
}
