//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetCapture.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATCRequestHeader
    {
        public int ID { get; set; }
        public string BatchID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> BudgetYrID { get; set; }
        public Nullable<int> BudgetTypeId { get; set; }
        public string RequestBy { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual BudgetMenuItem BudgetMenuItem { get; set; }
        public virtual BudgetYear BudgetYear { get; set; }
        public virtual Department Department { get; set; }
    }
}
