//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetCapture.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BudgetYear
    {
        public BudgetYear()
        {
            this.ListedSecurities = new HashSet<ListedSecurity>();
            this.Properties = new HashSet<Property>();
            this.ExistingStaffs = new HashSet<ExistingStaff>();
            this.ExpenseProjections = new HashSet<ExpenseProjection>();
            this.AssetBudgets = new HashSet<AssetBudget>();
            this.BudgetSummaryViews = new HashSet<BudgetSummaryView>();
            this.IndirectBudgets = new HashSet<IndirectBudget>();
            this.DirectBudgets = new HashSet<DirectBudget>();
            this.CapexBudgets = new HashSet<CapexBudget>();
            this.RevenueProjections = new HashSet<RevenueProjection>();
            this.ATCRequestHeaders = new HashSet<ATCRequestHeader>();
            this.GSS_Invoice = new HashSet<GSS_Invoice>();
        }
    
        public int ID { get; set; }
        public string Year { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<ListedSecurity> ListedSecurities { get; set; }
        public virtual ICollection<Property> Properties { get; set; }
        public virtual ICollection<ExistingStaff> ExistingStaffs { get; set; }
        public virtual ICollection<ExpenseProjection> ExpenseProjections { get; set; }
        public virtual ICollection<AssetBudget> AssetBudgets { get; set; }
        public virtual ICollection<BudgetSummaryView> BudgetSummaryViews { get; set; }
        public virtual ICollection<IndirectBudget> IndirectBudgets { get; set; }
        public virtual ICollection<DirectBudget> DirectBudgets { get; set; }
        public virtual ICollection<CapexBudget> CapexBudgets { get; set; }
        public virtual ICollection<RevenueProjection> RevenueProjections { get; set; }
        public virtual ICollection<ATCRequestHeader> ATCRequestHeaders { get; set; }
        public virtual ICollection<GSS_Invoice> GSS_Invoice { get; set; }
    }
}
