//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetCapture.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BudgetSummaryView
    {
        public int ID { get; set; }
        public string BudgetElement { get; set; }
        public Nullable<int> TotalNoCapture { get; set; }
        public Nullable<int> TotalPending { get; set; }
        public Nullable<int> TotalApproved { get; set; }
        public Nullable<decimal> TotalAmtPending { get; set; }
        public Nullable<decimal> TotalAmtApproved { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> BudgetYrID { get; set; }
    
        public virtual BudgetYear BudgetYear { get; set; }
        public virtual Department Department { get; set; }
    }
}
