//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetCapture.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CapexExpenseItem
    {
        public CapexExpenseItem()
        {
            this.CapexBudgets = new HashSet<CapexBudget>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<int> CapexTypeID { get; set; }
        public string DelFlg { get; set; }
    
        public virtual ICollection<CapexBudget> CapexBudgets { get; set; }
        public virtual CapexType CapexType { get; set; }
    }
}
