//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetCapture.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CapexType
    {
        public CapexType()
        {
            this.CapexExpenseItems = new HashSet<CapexExpenseItem>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string GLCode { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> BudgetYearID { get; set; }
    
        public virtual ICollection<CapexExpenseItem> CapexExpenseItems { get; set; }
    }
}
