//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetCapture.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerType
    {
        public CustomerType()
        {
            this.Customers = new HashSet<Customer>();
            this.RevenueProjections = new HashSet<RevenueProjection>();
            this.GSS_Customer = new HashSet<GSS_Customer>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<RevenueProjection> RevenueProjections { get; set; }
        public virtual ICollection<GSS_Customer> GSS_Customer { get; set; }
    }
}
