//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetCapture.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.ExistingStaffs = new HashSet<ExistingStaff>();
            this.AppUsers = new HashSet<AppUser>();
            this.ExpenseProjections = new HashSet<ExpenseProjection>();
            this.AssetBudgets = new HashSet<AssetBudget>();
            this.BudgetSummaryViews = new HashSet<BudgetSummaryView>();
            this.IndirectBudgets = new HashSet<IndirectBudget>();
            this.DirectBudgets = new HashSet<DirectBudget>();
            this.CapexBudgets = new HashSet<CapexBudget>();
            this.RevenueProjections = new HashSet<RevenueProjection>();
            this.ATCRequestHeaders = new HashSet<ATCRequestHeader>();
            this.IndirectBudgetATCs = new HashSet<IndirectBudgetATC>();
            this.DirectBudgetATCs = new HashSet<DirectBudgetATC>();
            this.AssetBudgetATCs = new HashSet<AssetBudgetATC>();
            this.CapexBudgetATCs = new HashSet<CapexBudgetATC>();
            this.ExistingStaffBudgetATCs = new HashSet<ExistingStaffBudgetATC>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<int> DirectorateID { get; set; }
    
        public virtual Directorate Directorate { get; set; }
        public virtual ICollection<ExistingStaff> ExistingStaffs { get; set; }
        public virtual ICollection<AppUser> AppUsers { get; set; }
        public virtual ICollection<ExpenseProjection> ExpenseProjections { get; set; }
        public virtual ICollection<AssetBudget> AssetBudgets { get; set; }
        public virtual ICollection<BudgetSummaryView> BudgetSummaryViews { get; set; }
        public virtual ICollection<IndirectBudget> IndirectBudgets { get; set; }
        public virtual ICollection<DirectBudget> DirectBudgets { get; set; }
        public virtual ICollection<CapexBudget> CapexBudgets { get; set; }
        public virtual ICollection<RevenueProjection> RevenueProjections { get; set; }
        public virtual ICollection<ATCRequestHeader> ATCRequestHeaders { get; set; }
        public virtual ICollection<IndirectBudgetATC> IndirectBudgetATCs { get; set; }
        public virtual ICollection<DirectBudgetATC> DirectBudgetATCs { get; set; }
        public virtual ICollection<AssetBudgetATC> AssetBudgetATCs { get; set; }
        public virtual ICollection<CapexBudgetATC> CapexBudgetATCs { get; set; }
        public virtual ICollection<ExistingStaffBudgetATC> ExistingStaffBudgetATCs { get; set; }
    }
}
