//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetCapture.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DirectExpenseItem
    {
        public DirectExpenseItem()
        {
            this.DirectBudgets = new HashSet<DirectBudget>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<int> DirectTypeID { get; set; }
        public string DelFlg { get; set; }
    
        public virtual ICollection<DirectBudget> DirectBudgets { get; set; }
        public virtual DirectType DirectType { get; set; }
    }
}
