//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetCapture.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseType
    {
        public ExpenseType()
        {
            this.ExpenseProjections = new HashSet<ExpenseProjection>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string GLCode { get; set; }
        public Nullable<int> DepartmentID { get; set; }
    
        public virtual ICollection<ExpenseProjection> ExpenseProjections { get; set; }
    }
}
