//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetCapture.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradeSalaryElement
    {
        public int SalElementID { get; set; }
        public int GradeId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual GradeSalaryElement GradeSalaryElement1 { get; set; }
        public virtual GradeSalaryElement GradeSalaryElement2 { get; set; }
    }
}
