//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetCapture.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSS_Customer
    {
        public GSS_Customer()
        {
            this.GSS_Invoice = new HashSet<GSS_Invoice>();
            this.GSS_SalesTbl = new HashSet<GSS_SalesTbl>();
        }
    
        public int ID { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress { get; set; }
        public Nullable<int> CustomerTypeID { get; set; }
        public string ContactPerson { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public Nullable<int> PipelineSectionID { get; set; }
        public Nullable<int> PaymentTermFlg { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> VATFlg { get; set; }
        public Nullable<decimal> MinimumOrderVolume { get; set; }
        public Nullable<bool> CapitalRecovery { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public string LastUpdatedBy { get; set; }
    
        public virtual CustomerType CustomerType { get; set; }
        public virtual GSS_PipelineSection GSS_PipelineSection { get; set; }
        public virtual ICollection<GSS_Invoice> GSS_Invoice { get; set; }
        public virtual ICollection<GSS_SalesTbl> GSS_SalesTbl { get; set; }
    }
}
