//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetCapture.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSS_Invoice
    {
        public int ID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> PeriodYear { get; set; }
        public Nullable<int> PeriodMonth { get; set; }
        public Nullable<decimal> TotalCertifiedVolume { get; set; }
        public Nullable<decimal> TotalInvoiceAmount { get; set; }
        public Nullable<decimal> TotalVAT { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual BudgetYear BudgetYear { get; set; }
        public virtual MonthOfYear MonthOfYear { get; set; }
        public virtual GSS_Customer GSS_Customer { get; set; }
    }
}
