//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetCapture.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSS_SalesTbl
    {
        public int ID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<decimal> CapturedVolumeSale { get; set; }
        public Nullable<System.DateTime> DateCaptured { get; set; }
        public Nullable<int> CapturedBy { get; set; }
        public Nullable<int> CapturedVolumeApprovedBy { get; set; }
        public Nullable<decimal> CertifiedVolumeSale { get; set; }
        public Nullable<System.DateTime> DateCertified { get; set; }
        public Nullable<int> CertifiedBy { get; set; }
        public Nullable<int> CertifiedApprovedby { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<decimal> InvoiceValue { get; set; }
        public Nullable<decimal> VatValue { get; set; }
        public Nullable<System.DateTime> DateInvoiced { get; set; }
        public Nullable<int> InvoicedBy { get; set; }
        public int TransactionPeriod { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual AppUser AppUser1 { get; set; }
        public virtual AppUser AppUser2 { get; set; }
        public virtual AppUser AppUser3 { get; set; }
        public virtual AppUser AppUser4 { get; set; }
        public virtual GSS_Customer GSS_Customer { get; set; }
    }
}
