//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetCapture.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RevenueProjection
    {
        public int ID { get; set; }
        public Nullable<int> BudgetYrID { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> MonthID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> CustomerTypeID { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
        public Nullable<int> Status { get; set; }
        public string EDApprover { get; set; }
        public string MDApprover { get; set; }
        public Nullable<System.DateTime> EDApprovalDate { get; set; }
        public Nullable<System.DateTime> MDApprovalDate { get; set; }
    
        public virtual BudgetYear BudgetYear { get; set; }
        public virtual CustomerType CustomerType { get; set; }
        public virtual Department Department { get; set; }
        public virtual MonthOfYear MonthOfYear { get; set; }
    }
}
