//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetCapture.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalBenCategory
    {
        public SalBenCategory()
        {
            this.SalaryElements = new HashSet<SalaryElement>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual ICollection<SalaryElement> SalaryElements { get; set; }
    }
}
